logging:
  level:
    ROOT: INFO
    org:
      hibernate:
        stat: debug
        type: trace

spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
    show-sql: true